create_clock -period 10.000 [get_ports {osc}]
create_generated_clock -source [get_ports -no_traverse osc] -edges {1 2 3} -edge_shift {0.000 43.553 87.105} [get_ports -no_traverse {clk}]
set_property -quiet IO_BUFFER_TYPE NONE [get_ports -quiet osc]
set_property -quiet CLOCK_BUFFER_TYPE NONE [get_ports -quiet osc]
set_property -quiet IS_IP_OOC_CELL TRUE [get_cells -of [get_ports -no_traverse -quiet clk]]
