# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/tyler_hyposvu/OneDrive - UW-Madison/Research/IARPA/QMOD_GDS/QMOD_GDS_Nexy/QMOD_GDS_Nexy.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1.xci
# IP: The module: 'clk_wiz_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/tyler_hyposvu/OneDrive - UW-Madison/Research/IARPA/QMOD_GDS/QMOD_GDS_Nexy/QMOD_GDS_Nexy.gen/sources_1/ip/clk_wiz_1/clk_wiz_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/tyler_hyposvu/OneDrive - UW-Madison/Research/IARPA/QMOD_GDS/QMOD_GDS_Nexy/QMOD_GDS_Nexy.gen/sources_1/ip/clk_wiz_1/clk_wiz_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/tyler_hyposvu/OneDrive - UW-Madison/Research/IARPA/QMOD_GDS/QMOD_GDS_Nexy/QMOD_GDS_Nexy.gen/sources_1/ip/clk_wiz_1/clk_wiz_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/tyler_hyposvu/OneDrive - UW-Madison/Research/IARPA/QMOD_GDS/QMOD_GDS_Nexy/QMOD_GDS_Nexy.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1.xci
# IP: The module: 'clk_wiz_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/tyler_hyposvu/OneDrive - UW-Madison/Research/IARPA/QMOD_GDS/QMOD_GDS_Nexy/QMOD_GDS_Nexy.gen/sources_1/ip/clk_wiz_1/clk_wiz_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/tyler_hyposvu/OneDrive - UW-Madison/Research/IARPA/QMOD_GDS/QMOD_GDS_Nexy/QMOD_GDS_Nexy.gen/sources_1/ip/clk_wiz_1/clk_wiz_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/tyler_hyposvu/OneDrive - UW-Madison/Research/IARPA/QMOD_GDS/QMOD_GDS_Nexy/QMOD_GDS_Nexy.gen/sources_1/ip/clk_wiz_1/clk_wiz_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
